// <auto-generated />
using System;
using ComplianceHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComplianceHub.Infrastructure.Data.Migrations.Regulations
{
    [DbContext(typeof(RegulationsDbContext))]
    [Migration("20260429101024_AddTriggerSourceToSyncHistory")]
    partial class AddTriggerSourceToSyncHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ChapterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("GovernmentEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GovernmentEntityId", "ChapterNumber")
                        .IsUnique();

                    b.ToTable("Agencies", (string)null);
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.GovernmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsImported")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSyncEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastAmendedDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastSyncedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TitleName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TitleNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TitleNumber")
                        .IsUnique();

                    b.ToTable("GovernmentEntities", (string)null);
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasFilter("\"ProcessedAt\" IS NULL");

                    b.ToTable("OutboxEvents", (string)null);
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.Regulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("GovernmentEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastAmendedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("RegulationCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegulationSubtypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegulationTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SectionNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("GovernmentEntityId");

                    b.HasIndex("RegulationCategoryId");

                    b.HasIndex("RegulationSubtypeId");

                    b.HasIndex("RegulationTypeId", "SectionNumber")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("Regulations", (string)null);
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.RegulationCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("GovernmentEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("SubchapterIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubchapterName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GovernmentEntityId");

                    b.HasIndex("AgencyId", "SubchapterIdentifier")
                        .IsUnique();

                    b.ToTable("RegulationCategories", (string)null);
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.RegulationChangeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChangeType")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RegulationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SectionNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegulationId", "Version");

                    b.ToTable("RegulationChangeHistory", (string)null);
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.RegulationChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("ArchivedVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GovernmentEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("GovernmentEntityName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("NewAmendedDate")
                        .HasColumnType("date");

                    b.Property<string>("NewContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NewHtmlContent")
                        .HasColumnType("text");

                    b.Property<int>("NewVersion")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("PreviousAmendedDate")
                        .HasColumnType("date");

                    b.Property<string>("PreviousContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PreviousHtmlContent")
                        .HasColumnType("text");

                    b.Property<Guid>("RegulationCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegulationCategoryName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("RegulationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegulationSubtypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegulationSubtypeName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("RegulationTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegulationTypeName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SectionNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SectionTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("GovernmentEntityId");

                    b.HasIndex("RegulationId");

                    b.ToTable("RegulationChangeLogs", (string)null);
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.RegulationSubtype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RegulationTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubpartIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubpartName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegulationTypeId", "SubpartIdentifier")
                        .IsUnique();

                    b.ToTable("RegulationSubtypes", (string)null);
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.RegulationSyncSchedulerHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChangedRecordsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DeactivatedRecordsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("GovernmentEntityId")
                        .HasColumnType("uuid");

                    b.Property<int>("ImportedRecordsCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OutboxEventsQueuedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Manual");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GovernmentEntityId", "StartedAt");

                    b.ToTable("RegulationSyncSchedulerHistory", (string)null);
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.RegulationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("GovernmentEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PartNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("RegulationCategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("GovernmentEntityId");

                    b.HasIndex("RegulationCategoryId", "PartNumber")
                        .IsUnique();

                    b.ToTable("RegulationTypes", (string)null);
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.Agency", b =>
                {
                    b.HasOne("ComplianceHub.Domain.Entities.Regulations.GovernmentEntity", "GovernmentEntity")
                        .WithMany("Agencies")
                        .HasForeignKey("GovernmentEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GovernmentEntity");
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.Regulation", b =>
                {
                    b.HasOne("ComplianceHub.Domain.Entities.Regulations.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplianceHub.Domain.Entities.Regulations.GovernmentEntity", "GovernmentEntity")
                        .WithMany()
                        .HasForeignKey("GovernmentEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplianceHub.Domain.Entities.Regulations.RegulationCategory", "RegulationCategory")
                        .WithMany()
                        .HasForeignKey("RegulationCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplianceHub.Domain.Entities.Regulations.RegulationSubtype", "RegulationSubtype")
                        .WithMany("Regulations")
                        .HasForeignKey("RegulationSubtypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ComplianceHub.Domain.Entities.Regulations.RegulationType", "RegulationType")
                        .WithMany("Regulations")
                        .HasForeignKey("RegulationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("GovernmentEntity");

                    b.Navigation("RegulationCategory");

                    b.Navigation("RegulationSubtype");

                    b.Navigation("RegulationType");
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.RegulationCategory", b =>
                {
                    b.HasOne("ComplianceHub.Domain.Entities.Regulations.Agency", "Agency")
                        .WithMany("RegulationCategories")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplianceHub.Domain.Entities.Regulations.GovernmentEntity", "GovernmentEntity")
                        .WithMany()
                        .HasForeignKey("GovernmentEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("GovernmentEntity");
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.RegulationChangeHistory", b =>
                {
                    b.HasOne("ComplianceHub.Domain.Entities.Regulations.Regulation", "Regulation")
                        .WithMany("ChangeHistory")
                        .HasForeignKey("RegulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regulation");
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.RegulationChangeLog", b =>
                {
                    b.HasOne("ComplianceHub.Domain.Entities.Regulations.Regulation", "Regulation")
                        .WithMany()
                        .HasForeignKey("RegulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regulation");
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.RegulationSubtype", b =>
                {
                    b.HasOne("ComplianceHub.Domain.Entities.Regulations.RegulationType", "RegulationType")
                        .WithMany("RegulationSubtypes")
                        .HasForeignKey("RegulationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegulationType");
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.RegulationSyncSchedulerHistory", b =>
                {
                    b.HasOne("ComplianceHub.Domain.Entities.Regulations.GovernmentEntity", "GovernmentEntity")
                        .WithMany()
                        .HasForeignKey("GovernmentEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GovernmentEntity");
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.RegulationType", b =>
                {
                    b.HasOne("ComplianceHub.Domain.Entities.Regulations.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplianceHub.Domain.Entities.Regulations.GovernmentEntity", "GovernmentEntity")
                        .WithMany()
                        .HasForeignKey("GovernmentEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComplianceHub.Domain.Entities.Regulations.RegulationCategory", "RegulationCategory")
                        .WithMany("RegulationTypes")
                        .HasForeignKey("RegulationCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("GovernmentEntity");

                    b.Navigation("RegulationCategory");
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.Agency", b =>
                {
                    b.Navigation("RegulationCategories");
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.GovernmentEntity", b =>
                {
                    b.Navigation("Agencies");
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.Regulation", b =>
                {
                    b.Navigation("ChangeHistory");
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.RegulationCategory", b =>
                {
                    b.Navigation("RegulationTypes");
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.RegulationSubtype", b =>
                {
                    b.Navigation("Regulations");
                });

            modelBuilder.Entity("ComplianceHub.Domain.Entities.Regulations.RegulationType", b =>
                {
                    b.Navigation("RegulationSubtypes");

                    b.Navigation("Regulations");
                });
#pragma warning restore 612, 618
        }
    }
}
